---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ include "gitea.serviceAccountName" . }}-anyuid"
subjects:
  - kind: ServiceAccount
    name: {{ include "gitea.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Values.postgresql.serviceAccount.name }}-anyuid"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.postgresql.serviceAccount.name }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'